config/routes.rb
Rails.application.routes.draw do
  get 'user_profile/show'
  resources :comments
  get 'search', to: "search#index"
  get 'profile/:id', to: 'user_profile#show', as: 'user_profile'

  root 'pages#home'
  resources :posts do
    resources :comments
  end

  resources :group_ownerships

  resources :groups do
    resources :group_memberships, only: [:create]
    put '/approve_membership/:id', to: 'group_memberships#approve', as: :approve_membership
    put '/reject_membership/:id', to: 'group_memberships#reject', as: :reject_membership
  end

  resources :groups do
    resources :posts
    resources :events do
      put :approve, on: :member
      put :reject, on: :member
    end
    post 'join', on: :member
    delete 'leave', on: :member
  end
  devise_for :users, controllers: { registrations: 'users/registrations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]

  # GET /comments or /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1 or /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments or /comments.json
  def create
    @comment = Comment.new(comment_params)
    @comment.user = current_user
    @comment.post = Post.find(params[:post_id])


    respond_to do |format|
      if @comment.save
        format.html { redirect_to comment_url(@comment), notice: "Comment was successfully created." }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to comment_url(@comment), notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to comments_url, notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:post_id, :user_id, :body)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
    <div class="user-posted-info" style="margin-top: 1rem;">
      <div class="user-posted">
        <% if comment.user.avatar.attached? %>
           <%= image_tag(comment.user.avatar, class: "profile-pic", style: "height: 2rem; width: 2rem; border-radius: 100%;")%>
        <% end %>
        <div style="white-space: nowrap; "><%= comment.user.displayname %></div>
        <div class="name-card-buttons">
          <% if comment.user == current_user%>
            <%= button_to comment, method: :delete, class: "destroy-button" do%>
              <%= render "groups/destroy-svg" %>
            <% end %>
          <% end %>
      </div>
      </div>

      <div>   <p> <%=  time_ago_in_words_with_units(comment.created_at) %></p> </div>
    </div>

       <%= comment.body %>
       <hr style="margin: .5rem 0px; ">

app/views/comments/_form.html.erb
<%= form_with(model: [post, comment], url: post_comments_path(post), class: "comment-form") do |form| %>
  <% if comment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="new-comment-container">
    <div>
      <%= form.text_area :body, class: "new-comment-text", placeholder: "Write your comment here..." %>
    </div>
    <div>
      <%= button_tag type: :submit, class: "new-comment-button" do %>
          <%= render "posts/create-svg" %> <!-- Replace this with your custom icon -->
        <% end %>
    </div>
  </div>
<% end %>

<style>

  .new-comment-container {
    border: 1px solid lightgray;
    padding: .5rem;

  }

  .new-comment-text {
    width: 100%;
    padding: .5rem;
    border: none;
  }

  .new-comment-button {
    border: none;
    background: transparent;
  }
</style>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Show this comment", @comment %> |
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Comments</h1>

<div id="comments">
  <% @comments.each do |comment| %>
    <%= render comment %>
    <p>
      <%= link_to "Show this comment", comment %>
    </p>
  <% end %>
</div>

<%= link_to "New comment", new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @comment %>

<div>
  <%= link_to "Edit this comment", edit_comment_path(@comment) %> |
  <%= link_to "Back to comments", comments_path %>

  <%= button_to "Destroy this comment", @comment, method: :delete %>
</div>