config/routes.rb
Rails.application.routes.draw do
  get 'user_profile/show'
  resources :comments
  get 'search', to: "search#index"
  get 'profile/:id', to: 'user_profile#show', as: 'user_profile'

  root 'pages#home'
  resources :posts do
    resources :comments
  end

  resources :group_ownerships

  resources :groups do
    resources :group_memberships, only: [:create]
    put '/approve_membership/:id', to: 'group_memberships#approve', as: :approve_membership
    put '/reject_membership/:id', to: 'group_memberships#reject', as: :reject_membership
  end

  resources :groups do
    resources :posts
    resources :events do
      put :approve, on: :member
      put :reject, on: :member
    end
    post 'join', on: :member
    delete 'leave', on: :member
  end
  devise_for :users, controllers: { registrations: 'users/registrations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/group.rb
class Group < ApplicationRecord
  has_and_belongs_to_many :users
  has_many :group_ownerships, dependent: :destroy
  has_many :owners, through: :group_ownerships, source: :user
  has_many :posts
  has_many :events
  has_one_attached :avatar

  def self.ransackable_attributes(auth_object = nil)
    ["name"]
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[ show edit update destroy join leave]

  # GET /groups or /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1 or /groups/1.json
  def show
    @post = @group.posts.build
  end

  # GET /groups/new
  def new
    @group = Group.new

  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups or /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        @group.users << current_user
        @group.owners << current_user


        format.html { redirect_to root_path, notice: "Group was successfully created." }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1 or /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to group_url(@group), notice: "Group was successfully updated." }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1 or /groups/1.json
  def destroy
    @group.destroy

    respond_to do |format|
      format.html { redirect_to root_path, notice: "Group was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def join
    @group.users << current_user
    redirect_to group_url(@group), notice: "You have joined the group."
  end

  def leave
     @group.users.delete(current_user)
     redirect_to group_url(@group), notice: "You have left the group."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def group_params
      params.require(:group).permit(:name, :avatar)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_destroy-svg.html.erb
<svg xmlns="http://www.w3.org/2000/svg" height="1em" viewBox="0 0 448 512"><!--! Font Awesome Free 6.4.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. --><path d="M135.2 17.7L128 32H32C14.3 32 0 46.3 0 64S14.3 96 32 96H416c17.7 0 32-14.3 32-32s-14.3-32-32-32H320l-7.2-14.3C307.4 6.8 296.3 0 284.2 0H163.8c-12.1 0-23.2 6.8-28.6 17.7zM416 128H32L53.2 467c1.6 25.3 22.6 45 47.9 45H346.9c25.3 0 46.3-19.7 47.9-45L416 128z"/></svg>

app/views/groups/_edit-svg.html.erb
<svg xmlns="http://www.w3.org/2000/svg" height="1em" viewBox="0 0 512 512"><!--! Font Awesome Free 6.4.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. --><path d="M410.3 231l11.3-11.3-33.9-33.9-62.1-62.1L291.7 89.8l-11.3 11.3-22.6 22.6L58.6 322.9c-10.4 10.4-18 23.3-22.2 37.4L1 480.7c-2.5 8.4-.2 17.5 6.1 23.7s15.3 8.5 23.7 6.1l120.3-35.4c14.1-4.2 27-11.8 37.4-22.2L387.7 253.7 410.3 231zM160 399.4l-9.1 22.7c-4 3.1-8.5 5.4-13.3 6.9L59.4 452l23-78.1c1.4-4.9 3.8-9.4 6.9-13.3l22.7-9.1v32c0 8.8 7.2 16 16 16h32zM362.7 18.7L348.3 33.2 325.7 55.8 314.3 67.1l33.9 33.9 62.1 62.1 33.9 33.9 11.3-11.3 22.6-22.6 14.5-14.5c25-25 25-65.5 0-90.5L453.3 18.7c-25-25-65.5-25-90.5 0zm-47.4 168l-144 144c-6.2 6.2-16.4 6.2-22.6 0s-6.2-16.4 0-22.6l144-144c6.2-6.2 16.4-6.2 22.6 0s6.2 16.4 0 22.6z"/></svg>

app/views/groups/_feed.html.erb
<% current_user.groups.each do |group|%>
    <%= link_to group.name, group_path(group)%>
     <h3>Members: </h3>
  <ul>
    <% group.users.each do |user| %>
      <li><%= user.displayname%></li>
    <% end %>
  </ul>
<% end %>

app/views/groups/_form.html.erb
<%= form_with(model: group) do |form| %>
  <% if group.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
        <% group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :avatar %><br />
    <%= form.file_field :avatar %>
  </div>


  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/groups/_group.html.erb
<div id="<%= dom_id group %>" class="group-main">

  <div class="name-card">
     <div class="name-card-upper">
      <% if group.avatar.attached? %>
        <%= image_tag(group.avatar, class: "group-profile-pic")%>
      <% else %>
        No Profile Image
      <% end %>
    </div>
    <div class="name-card-lower">
      <p>
        <h3><%= group.name %></h3>
      </p>
      <div><%= group.users.count %> Members</div>
      <div>
        Owners:
        <% group.owners.each do |owner|%>
          <%= owner.displayname %><br>
        <% end %>
      </div>
       <div class="name-card-buttons">
       <% if group.users.include?(current_user)%>
          <%= button_to leave_group_path(group), method: :delete, class: "leave-group-button" do %>
            <%= render "groups/leave-svg"%>
          <% end %>
       <% else %>
          <%= button_to join_group_path(group), method: :post, class: "join-group-button" do %>
            <%= render "groups/join-svg"%>
          <% end %>
       <% end %>
       <% if group.owners.include?(current_user)%>
            <%= button_to @group, method: :delete, class: "destroy-button" do%>
              <%= render "groups/destroy-svg"%>
            <% end %>
            <%= button_to edit_group_path(@group), method: :get, class: "edit-button",  data: { turbo_frame: "remote_modal" }  do %>
              <%= render "groups/edit-svg"%>
            <% end %>
        <% end %>
       </div>
    </div>

  </div>


  <div class="group-members">
    <h3>Members</h3>
    <ul>
      <% group.users.limit(5).each do |user| %>
        <li class="member-list">
         <% if user.avatar.attached? %>
          <%= image_tag(user.avatar, style: "height: 2rem; width: 2rem;")%>
         <% end %>
        <div class="user-info">
          <%= user.displayname%>
          <span class="member-username"><%= user.username %></span>
        </div>
        </li>
      <% end %>
    </ul>
  </div>

  <style>
  /* Hide the comments container by default */
  .comments {
    display: none;
  }

  /* Show the comments container when the "show" class is present */
  .comments.show {
    display: block;
  }
</style>







  <div class="group-posts">
    <h3>Posts </h3>
    <% if group.users.include?(current_user)%>
      <%= render partial: "posts/form", locals: { group: @group, post: @post }  %>
    <% end %>
    <% if group.posts.any? %>
    <% group.posts.where.not(created_at: nil).sort_by(&:created_at).reverse.each do |post| %>
      <div class="group-post">

         <% if group.users.include?(current_user) && post.user.present?%>
          <div class="user-posted-info">

            <div class="user-posted">
              <% if post.user.avatar.attached? %>
                <%= image_tag(post.user.avatar, class: "profile-pic", style: "height: 2rem; width: 2rem; border-radius: 100%;")%>
              <% else %>
                No image found
              <% end %>
              <p><%= post.user.displayname %></p>
            </div>

            <div class="name-card-buttons">
              <% if post.user == current_user%>
                  <%= button_to post, method: :delete, class: "destroy-button" do%>
                    <%= render "groups/destroy-svg"%>
                  <% end %>
                  <%= button_to edit_post_path(post), method: :get, class: "edit-button", data: { turbo_frame: "remote_modal" } do%>
                    <%= render "groups/edit-svg" %>
                  <% end %>
              <% end %>
              </div>

            <div>
              <p> <%=  time_ago_in_words_with_units(post.created_at) %></p>
            </div>
          </div>
        <% end %>


        <div>
          <%= post.body %>
           <% post.images.each do |image| %>
           <%= image_tag image, style: "width: 100%;"%>
          <% end %>
        </div>


           <%= button_tag "Show Comments", class: "show-comments-button" %>

          <div class="comments">
            <div class="new-comment">
                <%= render partial: "comments/form", locals: { post: post, comment: Comment.new } %>
            </div>
            <div class="comment">
              <% post.comments.each do |comment|%>
                <%= render partial: "comments/comment", locals: {comment: comment}%>
              <% end %>
            </div>
          </div>
      </div>
    <% end %>

    <% end %>
  </div>



   <div class="group-events">
     <div class="events-header">
       <h3>Events </h3>
       <% if group.users.include?(current_user) %>
        <%= link_to new_group_event_path(group),  data: { turbo_frame: "remote_modal" }  do %>
          <%= render "posts/create-svg"%>
        <% end %>
       <% end %>
        </div>
       <% group.events.each do |event| %>
         <%= link_to event.title, group_event_path(group, event), data: { turbo_frame: "remote_modal" } %>
      <div class="event-options">
        <p>Created by: <%= event.user.email %></p>
        <% if event.user == current_user || group.owners.include?(current_user)%>
          <% if event.pending? %>
          <div>Pending approval</div>
          <% end %>
           <%= button_to group_event_path(group, event), method: :delete, class: "event-destroy-button" do%>
                <%= render "groups/destroy-svg"%>
              <% end %>
         </div>
        <% end %>
      <% end %>
   </div>





</div>

app/views/groups/_join-svg.html.erb
<svg xmlns="http://www.w3.org/2000/svg" height="1em" viewBox="0 0 640 512"><!--! Font Awesome Free 6.4.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. --><path d="M96 128a128 128 0 1 1 256 0A128 128 0 1 1 96 128zM0 482.3C0 383.8 79.8 304 178.3 304h91.4C368.2 304 448 383.8 448 482.3c0 16.4-13.3 29.7-29.7 29.7H29.7C13.3 512 0 498.7 0 482.3zM609.3 512H471.4c5.4-9.4 8.6-20.3 8.6-32v-8c0-60.7-27.1-115.2-69.8-151.8c2.4-.1 4.7-.2 7.1-.2h61.4C567.8 320 640 392.2 640 481.3c0 17-13.8 30.7-30.7 30.7zM432 256c-31 0-59-12.6-79.3-32.9C372.4 196.5 384 163.6 384 128c0-26.8-6.6-52.1-18.3-74.3C384.3 40.1 407.2 32 432 32c61.9 0 112 50.1 112 112s-50.1 112-112 112z"/></svg>

app/views/groups/_leave-svg.html.erb
<svg xmlns="http://www.w3.org/2000/svg" height="1em" viewBox="0 0 640 512"><!--! Font Awesome Free 6.4.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. --><path d="M208 96a48 48 0 1 0 0-96 48 48 0 1 0 0 96zM123.7 200.5c1-.4 1.9-.8 2.9-1.2l-16.9 63.5c-5.6 21.1-.1 43.6 14.7 59.7l70.7 77.1 22 88.1c4.3 17.1 21.7 27.6 38.8 23.3s27.6-21.7 23.3-38.8l-23-92.1c-1.9-7.8-5.8-14.9-11.2-20.8l-49.5-54 19.3-65.5 9.6 23c4.4 10.6 12.5 19.3 22.8 24.5l26.7 13.3c15.8 7.9 35 1.5 42.9-14.3s1.5-35-14.3-42.9L281 232.7l-15.3-36.8C248.5 154.8 208.3 128 163.7 128c-22.8 0-45.3 4.8-66.1 14l-8 3.5c-32.9 14.6-58.1 42.4-69.4 76.5l-2.6 7.8c-5.6 16.8 3.5 34.9 20.2 40.5s34.9-3.5 40.5-20.2l2.6-7.8c5.7-17.1 18.3-30.9 34.7-38.2l8-3.5zm-30 135.1L68.7 398 9.4 457.4c-12.5 12.5-12.5 32.8 0 45.3s32.8 12.5 45.3 0L116.3 441c4.6-4.6 8.2-10.1 10.6-16.1l14.5-36.2-40.7-44.4c-2.5-2.7-4.8-5.6-7-8.6zM550.6 153.4c-12.5-12.5-32.8-12.5-45.3 0s-12.5 32.8 0 45.3L530.7 224H384c-17.7 0-32 14.3-32 32s14.3 32 32 32H530.7l-25.4 25.4c-12.5 12.5-12.5 32.8 0 45.3s32.8 12.5 45.3 0l80-80c12.5-12.5 12.5-32.8 0-45.3l-80-80z"/></svg>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render "events/remote_modal", title: "Edit Post" do %>
  <%= render "form", group: @group %>
<% end %>

app/views/groups/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Groups</h1>

<div id="groups">
  <% @groups.each do |group| %>
    <%= render group %>
    <p>
      <%= link_to "Show this group", group %>
    </p>
  <% end %>
</div>

<%= link_to "New group", new_group_path %>

app/views/groups/new.html.erb
<h1>New group</h1>

<%= render "form", group: @group %>

<br>

<div>
  <%= link_to "Back to groups", groups_path %>
</div>

app/views/groups/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @group %>